### ISSUE TITLE
Configurable Week Start

### ISSUE THREAD

**Issue by mbrown1413** [mbrown1413/Dont-Break-The-Chain#3]
Weeks currently start on Sunday, but should be configurable to start on any day.

As far as the web interface, I'm thinking the section at the bottom where you can select the start date should be titled "Advanced Options" or something. Then we can add an option for day of the week, and anything else we think of in the future.

**Comment by juliabla** [comment]
Hej, will this be implemented soon? Monday as the start of the week would also be the ISO norm.

**Comment by mbrown1413** [comment]
Looks like a pretty simple feature to add. I have some time today so I'll get it implemented soon.

**Comment by juliabla** [comment]
Thank you and also thanks for the calendar, Michael! :)

**Comment by mbrown1413** [comment]
:smile: No problem, just glad to see people using this.

Try now. The default is Monday but it's configurable in the advanced options at the bottom.

**Comment by juliabla** [comment]
Nice, thanks!
